"""
Static lookup tables for rule-based relevance/sector/ticker classification.

This is the piece that needs the most ongoing maintenance - update as
companies list/delist, and as new macro terms become relevant. Each
entry maps one or more common name variants (aliases) to a canonical
name and sector, since headlines refer to the same company differently
depending on the outlet (e.g. "Maybank" vs "Malayan Banking Bhd").

Structure: BURSA_TICKERS maps alias -> (canonical_name, sector).
Add every phrasing you actually see in real headlines here - the
scorer.py "unmatched entities" log output tells you what's being missed.

Ticker codes (e.g. "0270" for NationGate) are included as aliases so
that headlines referencing "0270 NATGATE" or announcements with pure
codes still match.

WARNING on short aliases: Any alias <= 4 chars is at risk of false-
positive matches even with \b word-boundary. Flagged inline with # AMB
comments. Consider requiring context (e.g. "MISC Bhd") for these.
"""

BURSA_TICKERS = {
    # ═══════════════════════════════════════════════════════════════
    # BANKING (FBM KLCI heavyweights - most market-moving sector)
    # ═══════════════════════════════════════════════════════════════
    "Maybank": ("Maybank", "Banking"),
    "Malayan Banking": ("Maybank", "Banking"),
    "Malayan Banking Bhd": ("Maybank", "Banking"),
    "1155": ("Maybank", "Banking"),
    "Public Bank": ("Public Bank", "Banking"),
    "1295": ("Public Bank", "Banking"),
    "CIMB": ("CIMB", "Banking"),
    "CIMB Group": ("CIMB", "Banking"),
    "1023": ("CIMB", "Banking"),
    "RHB": ("RHB Bank", "Banking"),
    "RHB Bank": ("RHB Bank", "Banking"),
    "RHB Banking": ("RHB Bank", "Banking"),
    "1066": ("RHB Bank", "Banking"),
    "5819": ("Hong Leong Bank", "Banking"),
    "Hong Leong Financial": ("Hong Leong Financial Group", "Banking"),
    "HLFG": ("Hong Leong Financial Group", "Banking"),
    "AMMB": ("AmBank", "Banking"),
    "AmBank": ("AmBank", "Banking"),
    "Ambank": ("AmBank", "Banking"),
    "1015": ("AmBank", "Banking"),
    "Affin Bank": ("Affin Bank", "Banking"),
    "Affin Group": ("Affin Bank", "Banking"),
    "5185": ("Affin Bank", "Banking"),
    "Alliance Bank": ("Alliance Bank", "Banking"),
    "2488": ("Alliance Bank", "Banking"),
    "Bank Islam": ("Bank Islam", "Banking"),
    "BIMB": ("Bank Islam", "Banking"),
    "5258": ("Bank Islam", "Banking"),
    "MBSB": ("MBSB Bank", "Banking"),
    "MBSB Bank": ("MBSB Bank", "Banking"),
    "1171": ("MBSB Bank", "Banking"),
    "SK Hynix": ("SK Hynix", "Tech"),  # relevant to MY semicon supply chain
    "Super Micro": ("Super Micro", "Tech"),  # AI server maker, relevant
    "Godrej Consumer": ("Godrej Consumer", "Consumer"),  # emerging markets peer
    "MN Holdings": ("MN Holdings", "Construction"),   # from the news
    "Inta Bina": ("Inta Bina", "Construction"),       # from the news
    "Hextar Retail": ("Hextar Retail", "Consumer"),   # from the news
    "AME Elite": ("AME Elite Consortium", "Property"),
    "Hup Seng": ("Hup Seng Industries", "Consumer"),
    "Well Chip": ("Well Chip Group", "Industrial"),
    "ITMAX System": ("ITMAX System", "Tech"),
    "SD Guthrie": ("SD Guthrie", "Plantation"),        # Sime Darby Guthrie
    "Sabah Electricity": ("Sabah Electricity", "Utilities"),
    "Amona Group": ("Amona Group", "Property"),
    "MTT Shipping": ("MTT Shipping and Logistics", "Transport"),
    "Stratus Global": ("Stratus Global Holdings", "Industrial"),
    "Industronics": ("Industronics", "Tech"),
    "Tabung Haji": ("Tabung Haji", "GLC"),   # or "Politics" or "Macro"
    "Lembaga Tabung Haji": ("Tabung Haji", "GLC"),
    "EPF": ("EPF", "GLC"),
    "Employees Provident Fund": ("EPF", "GLC"),
    "KWSP": ("EPF", "GLC"),
    "KWAP": ("KWAP", "GLC"),
    "Kumpulan Wang Persaraan": ("KWAP", "GLC"),
    "PNB": ("PNB", "GLC"),
    "Permodalan Nasional Berhad": ("PNB", "GLC"),
    "ASB": ("ASB", "GLC"),  # Amanah Saham Bumiputera
    "Amanah Saham Bumiputera": ("ASB", "GLC"),
    "Khazanah": ("Khazanah Nasional", "GLC"),
    "Khazanah Nasional": ("Khazanah Nasional", "GLC"),
    "MOF Inc": ("MOF Inc", "GLC"),
    "Retirement Fund Inc": ("KWAP", "GLC"),
    "Social Security Organisation": ("SOCSO", "GLC"),
    "SOCSO": ("SOCSO", "GLC"),
    "PERKESO": ("SOCSO", "GLC"),    


    # ═══════════════════════════════════════════════════════════════
    # PLANTATION (CPO-driven, weather + Indonesia sensitive)
    # ═══════════════════════════════════════════════════════════════
    "IOI Corp": ("IOI Corp", "Plantation"),
    "IOI Corporation": ("IOI Corp", "Plantation"),
    "IOICORP": ("IOI Corp", "Plantation"),
    "1961": ("IOI Corp", "Plantation"),
    "KLK": ("KLK", "Plantation"),
    "Kuala Lumpur Kepong": ("KLK", "Plantation"),
    "2445": ("KLK", "Plantation"),
    "Sime Darby Plantation": ("Sime Darby Plantation", "Plantation"),
    "SD Plantation": ("Sime Darby Plantation", "Plantation"),
    "SDPL": ("Sime Darby Plantation", "Plantation"),
    "5285": ("Sime Darby Plantation", "Plantation"),
    "SIMEPLT": ("Sime Darby Plantation", "Plantation"),
    "FGV": ("FGV", "Plantation"),
    "FGV Holdings": ("FGV", "Plantation"),
    "FGV Palm": ("FGV", "Plantation"),
    "5222": ("FGV", "Plantation"),
    "Genting Plantations": ("Genting Plantations", "Plantation"),
    "GENP": ("Genting Plantations", "Plantation"),
    "2291": ("Genting Plantations", "Plantation"),
    "United Plantations": ("United Plantations", "Plantation"),
    "UTDPLT": ("United Plantations", "Plantation"),
    "2089": ("United Plantations", "Plantation"),
    "TSH Resources": ("TSH Resources", "Plantation"),
    "9059": ("TSH Resources", "Plantation"),
    "Ta Ann": ("Ta Ann Holdings", "Plantation"),
    "5012": ("Ta Ann Holdings", "Plantation"),
    "Hap Seng Plantations": ("Hap Seng Plantations", "Plantation"),
    "5138": ("Hap Seng Plantations", "Plantation"),
    "Sarawak Oil Palms": ("Sarawak Oil Palms", "Plantation"),
    "5126": ("Sarawak Oil Palms", "Plantation"),
    "Kim Loong Resources": ("Kim Loong Resources", "Plantation"),
    "5027": ("Kim Loong Resources", "Plantation"),

    # ═══════════════════════════════════════════════════════════════
    # OIL & GAS (Brent/WTI sensitive, plus MY-specific players)
    # ═══════════════════════════════════════════════════════════════
    "Petronas": ("Petronas", "OilGas"),
    "Petroliam Nasional": ("Petronas", "OilGas"),
    "Petronas Chemicals": ("Petronas Chemicals", "OilGas"),
    "PChem": ("Petronas Chemicals", "OilGas"),
    "PCHEM": ("Petronas Chemicals", "OilGas"),
    "5183": ("Petronas Chemicals", "OilGas"),
    "Petronas Gas": ("Petronas Gas", "OilGas"),
    "PetGas": ("Petronas Gas", "OilGas"),
    "PETGAS": ("Petronas Gas", "OilGas"),
    "6033": ("Petronas Gas", "OilGas"),
    "Petronas Dagangan": ("Petronas Dagangan", "OilGas"),
    "PetDag": ("Petronas Dagangan", "OilGas"),
    "PETDAG": ("Petronas Dagangan", "OilGas"),
    "5681": ("Petronas Dagangan", "OilGas"),
    "Dialog Group": ("Dialog Group", "OilGas"),
    "Dialog": ("Dialog Group", "OilGas"),
    "7277": ("Dialog Group", "OilGas"),
    "Yinson": ("Yinson", "OilGas"),
    "Yinson Holdings": ("Yinson", "OilGas"),
    "7293": ("Yinson", "OilGas"),
    "Bumi Armada": ("Bumi Armada", "OilGas"),
    "5210": ("Bumi Armada", "OilGas"),
    "MISC Berhad": ("MISC", "OilGas"),
    "MISC Bhd": ("MISC", "OilGas"),
    "3816": ("MISC", "OilGas"),
    "Hibiscus Petroleum": ("Hibiscus", "OilGas"),
    "Hibiscus": ("Hibiscus", "OilGas"),
    "5199": ("Hibiscus", "OilGas"),
    "Velesto Energy": ("Velesto Energy", "OilGas"),
    "Velesto": ("Velesto Energy", "OilGas"),
    "5243": ("Velesto Energy", "OilGas"),
    "Sapura Energy": ("Sapura Energy", "OilGas"),
    "Sapura": ("Sapura Energy", "OilGas"),
    "5218": ("Sapura Energy", "OilGas"),
    "Wasco": ("Wasco", "OilGas"),
    "5142": ("Wasco", "OilGas"),
    "Deleum": ("Deleum", "OilGas"),
    "5132": ("Deleum", "OilGas"),
    "Uzma": ("Uzma", "OilGas"),
    "7250": ("Uzma", "OilGas"),
    "Reservoir Link": ("Reservoir Link", "OilGas"),
    "0219": ("Reservoir Link", "OilGas"),
    "Icon Offshore": ("Icon Offshore", "OilGas"),
    "5255": ("Icon Offshore", "OilGas"),
    "T7 Global": ("T7 Global", "OilGas"),
    "7228": ("T7 Global", "OilGas"),

    # ═══════════════════════════════════════════════════════════════
    # UTILITIES (regulated, dividend-heavy, energy transition beneficiaries)
    # ═══════════════════════════════════════════════════════════════
    "Tenaga Nasional": ("Tenaga Nasional", "Utilities"),
    "TNB": ("Tenaga Nasional", "Utilities"),
    "5347": ("Tenaga Nasional", "Utilities"),
    "YTL Power": ("YTL Power", "Utilities"),
    "YTL Power International": ("YTL Power", "Utilities"),
    "YTLPOWR": ("YTL Power", "Utilities"),
    "6742": ("YTL Power", "Utilities"),
    "Malakoff": ("Malakoff", "Utilities"),
    "5264": ("Malakoff", "Utilities"),
    "Gas Malaysia": ("Gas Malaysia", "Utilities"),
    "5209": ("Gas Malaysia", "Utilities"),
    "Ranhill Utilities": ("Ranhill Utilities", "Utilities"),
    "5272": ("Ranhill Utilities", "Utilities"),

    # ═══════════════════════════════════════════════════════════════
    # TELCO (5G, digital infrastructure)
    # ═══════════════════════════════════════════════════════════════
    "Telekom Malaysia": ("Telekom Malaysia", "Telco"),
    "TM Berhad": ("Telekom Malaysia", "Telco"),
    "TM Bhd": ("Telekom Malaysia", "Telco"),
    "4863": ("Telekom Malaysia", "Telco"),
    "Axiata": ("Axiata", "Telco"),
    "Axiata Group": ("Axiata", "Telco"),
    "6888": ("Axiata", "Telco"),
    "Maxis": ("Maxis", "Telco"),
    "Maxis Bhd": ("Maxis", "Telco"),
    "6012": ("Maxis", "Telco"),
    "CelcomDigi": ("CelcomDigi", "Telco"),
    "6947": ("CelcomDigi", "Telco"),
    "Time dotCom": ("Time dotCom", "Telco"),
    "TdC": ("Time dotCom", "Telco"),
    "5031": ("Time dotCom", "Telco"),
    "OCK Group": ("OCK Group", "Telco"),
    "0172": ("OCK Group", "Telco"),
    "Redtone Digital": ("Redtone Digital", "Telco"),
    "0032": ("Redtone Digital", "Telco"),

    # ═══════════════════════════════════════════════════════════════
    # TECH / SEMICON / DATA CENTER (hot theme 2024-26)
    # ═══════════════════════════════════════════════════════════════
    "NationGate": ("NationGate", "Tech"),
    "NATGATE": ("NationGate", "Tech"),
    "Nation Gate": ("NationGate", "Tech"),
    "0270": ("NationGate", "Tech"),
    "Inari Amertron": ("Inari Amertron", "Tech"),
    "Inari": ("Inari Amertron", "Tech"),
    "0166": ("Inari Amertron", "Tech"),
    "Frontken": ("Frontken", "Tech"),
    "Frontken Corp": ("Frontken", "Tech"),
    "0128": ("Frontken", "Tech"),
    "Mi Technovation": ("Mi Technovation", "Tech"),
    "MI Technovation": ("Mi Technovation", "Tech"),
    "Vitrox": ("Vitrox", "Tech"),
    "ViTrox": ("Vitrox", "Tech"),
    "0097": ("Vitrox", "Tech"),
    "Datasonic": ("Datasonic", "Tech"),
    "5216": ("Datasonic", "Tech"),
    "Globetronics": ("Globetronics", "Tech"),
    "7022": ("Globetronics", "Tech"),
    "Genetec Technology": ("Genetec Technology", "Tech"),
    "Genetec": ("Genetec Technology", "Tech"),
    "0104": ("Genetec Technology", "Tech"),
    "Greatech": ("Greatech Technology", "Tech"),
    "Greatech Technology": ("Greatech Technology", "Tech"),
    "0208": ("Greatech Technology", "Tech"),
    "UWC": ("UWC", "Tech"),
    "UWC Bhd": ("UWC", "Tech"),
    "5292": ("UWC", "Tech"),
    "Pentamaster": ("Pentamaster", "Tech"),
    "Pentamaster Corporation": ("Pentamaster", "Tech"),
    "7160": ("Pentamaster", "Tech"),
    "KESM Industries": ("KESM Industries", "Tech"),
    "KESM": ("KESM Industries", "Tech"),
    "9334": ("KESM Industries", "Tech"),
    "Malaysian Pacific Industries": ("MPI", "Tech"),
    "3867": ("MPI", "Tech"),
    "Unisem": ("Unisem", "Tech"),
    "5005": ("Unisem", "Tech"),
    "D&O Green Technologies": ("D&O Green", "Tech"),
    "7204": ("D&O Green", "Tech"),
    "JHM Consolidation": ("JHM Consolidation", "Tech"),
    "JHM": ("JHM Consolidation", "Tech"),
    "0127": ("JHM Consolidation", "Tech"),
    "Aemulus": ("Aemulus Holdings", "Tech"),
    "0181": ("Aemulus Holdings", "Tech"),
    "Elsoft Research": ("Elsoft Research", "Tech"),
    "0090": ("Elsoft Research", "Tech"),
    "MyEG Services": ("MyEG Services", "Tech"),
    "MyEG": ("MyEG Services", "Tech"),
    "0138": ("MyEG Services", "Tech"),  # NOTE: conflict with Mi Technovation - verify
    "GHL Systems": ("GHL Systems", "Tech"),
    "0021": ("GHL Systems", "Tech"),
    "Revenue Group": ("Revenue Group", "Tech"),
    "0200": ("Revenue Group", "Tech"),

    # ═══════════════════════════════════════════════════════════════
    # HEALTHCARE (hospitals + gloves)
    # ═══════════════════════════════════════════════════════════════
    "IHH": ("IHH Healthcare", "Healthcare"),
    "5225": ("IHH Healthcare", "Healthcare"),
    "KPJ Healthcare": ("KPJ Healthcare", "Healthcare"),
    "5878": ("KPJ Healthcare", "Healthcare"),
    "Top Glove": ("Top Glove", "Gloves"),
    "Top Glove Corporation": ("Top Glove", "Gloves"),
    "7113": ("Top Glove", "Gloves"),
    "Hartalega": ("Hartalega", "Gloves"),
    "Hartalega Holdings": ("Hartalega", "Gloves"),
    "5168": ("Hartalega", "Gloves"),
    "Kossan": ("Kossan Rubber", "Gloves"),
    "Kossan Rubber": ("Kossan Rubber", "Gloves"),
    "7153": ("Kossan Rubber", "Gloves"),
    "Supermax": ("Supermax", "Gloves"),
    "Supermax Corporation": ("Supermax", "Gloves"),
    "7106": ("Supermax", "Gloves"),
    "Careplus Group": ("Careplus Group", "Gloves"),
    "0163": ("Careplus Group", "Gloves"),
    "Comfort Gloves": ("Comfort Gloves", "Gloves"),
    "2127": ("Comfort Gloves", "Gloves"),
    "Duopharma Biotech": ("Duopharma Biotech", "Healthcare"),
    "Duopharma": ("Duopharma Biotech", "Healthcare"),
    "7148": ("Duopharma Biotech", "Healthcare"),
    "Pharmaniaga": ("Pharmaniaga", "Healthcare"),
    "7081": ("Pharmaniaga", "Healthcare"),
    "Kotra Industries": ("Kotra Industries", "Healthcare"),
    "0002": ("Kotra Industries", "Healthcare"),

    # ═══════════════════════════════════════════════════════════════
    # CONSUMER (defensive, dividend-friendly)
    # ═══════════════════════════════════════════════════════════════
    "Nestle Malaysia": ("Nestle Malaysia", "Consumer"),
    "Nestle": ("Nestle Malaysia", "Consumer"),
    "4707": ("Nestle Malaysia", "Consumer"),
    "QL Resources": ("QL Resources", "Consumer"),
    "7084": ("QL Resources", "Consumer"),
    "Fraser & Neave": ("F&N", "Consumer"),
    "F&N": ("F&N", "Consumer"),
    "FNH": ("F&N", "Consumer"),  # AMB
    "3689": ("F&N", "Consumer"),
    "Mr DIY": ("MRDIY", "Consumer"),
    "MRDIY": ("MRDIY", "Consumer"),
    "MR D.I.Y": ("MRDIY", "Consumer"),
    "5296": ("MRDIY", "Consumer"),
    "Padini": ("Padini", "Consumer"),
    "Padini Holdings": ("Padini", "Consumer"),
    "7052": ("Padini", "Consumer"),
    "Aeon": ("Aeon", "Consumer"),
    "AEON Co": ("Aeon", "Consumer"),
    "6599": ("Aeon", "Consumer"),
    "Berjaya Food": ("Berjaya Food", "Consumer"),
    "BJFood": ("Berjaya Food", "Consumer"),
    "5196": ("Berjaya Food", "Consumer"),
    "7-Eleven Malaysia": ("7-Eleven Malaysia", "Consumer"),
    "5250": ("7-Eleven Malaysia", "Consumer"),
    "Farm Fresh": ("Farm Fresh", "Consumer"),
    "5306": ("Farm Fresh", "Consumer"),
    "Dutch Lady Milk": ("Dutch Lady", "Consumer"),
    "Dutch Lady": ("Dutch Lady", "Consumer"),
    "3026": ("Dutch Lady", "Consumer"),
    "Guan Chong": ("Guan Chong", "Consumer"),
    "5102": ("Guan Chong", "Consumer"),
    "PPB Group": ("PPB Group", "Consumer"),
    "PPB": ("PPB Group", "Consumer"),
    "4065": ("PPB Group", "Consumer"),
    "Carlsberg": ("Carlsberg Malaysia", "Consumer"),
    "Carlsberg Malaysia": ("Carlsberg Malaysia", "Consumer"),
    "2836": ("Carlsberg Malaysia", "Consumer"),
    "Heineken Malaysia": ("Heineken Malaysia", "Consumer"),
    "3255": ("Heineken Malaysia", "Consumer"),
    "British American Tobacco": ("BAT Malaysia", "Consumer"),
    "BAT Malaysia": ("BAT Malaysia", "Consumer"),
    "4162": ("BAT Malaysia", "Consumer"),
    "Power Root": ("Power Root", "Consumer"),
    "7237": ("Power Root", "Consumer"),
    "Oldtown": ("Oldtown Berhad", "Consumer"),
    "5201": ("Oldtown Berhad", "Consumer"),

    # ═══════════════════════════════════════════════════════════════
    # CONSTRUCTION (infra spending, MRT, HSR beneficiaries)
    # ═══════════════════════════════════════════════════════════════
    "Gamuda": ("Gamuda", "Construction"),
    "Gamuda Bhd": ("Gamuda", "Construction"),
    "5398": ("Gamuda", "Construction"),
    "IJM Corporation": ("IJM Corp", "Construction"),
    "IJM": ("IJM Corp", "Construction"),  # AMB
    "3336": ("IJM Corp", "Construction"),
    "Sunway Construction": ("Sunway Construction", "Construction"),
    "SunCon": ("Sunway Construction", "Construction"),
    "SUNCON": ("Sunway Construction", "Construction"),
    "5263": ("Sunway Construction", "Construction"),
    "9679": ("WCT Holdings", "Construction"),
    "Kerjaya Prospek": ("Kerjaya Prospek", "Construction"),
    "Kerjaya": ("Kerjaya Prospek", "Construction"),
    "7161": ("Kerjaya Prospek", "Construction"),
    "MRCB": ("MRCB", "Construction"),
    "Malaysian Resources Corporation": ("MRCB", "Construction"),
    "1651": ("MRCB", "Construction"),
    "Muhibbah Engineering": ("Muhibbah Engineering", "Construction"),
    "5703": ("Muhibbah Engineering", "Construction"),
    "Ekovest": ("Ekovest", "Construction"),
    "8877": ("Ekovest", "Construction"),
    "Advancecon": ("Advancecon", "Construction"),
    "5281": ("Advancecon", "Construction"),
    "Gadang": ("Gadang Holdings", "Construction"),
    "9261": ("Gadang Holdings", "Construction"),
    "Econpile": ("Econpile Holdings", "Construction"),
    "5253": ("Econpile Holdings", "Construction"),

    # ═══════════════════════════════════════════════════════════════
    # PROPERTY (JS-SEZ + Johor beneficiaries in focus)
    # ═══════════════════════════════════════════════════════════════
    "Sunway Bhd": ("Sunway", "Property"),
    "Sunway Berhad": ("Sunway", "Property"),
    "5211": ("Sunway", "Property"),
    "SP Setia": ("SP Setia", "Property"),
    "S P Setia": ("SP Setia", "Property"),
    "8664": ("SP Setia", "Property"),
    "Mah Sing": ("Mah Sing", "Property"),
    "Mah Sing Group": ("Mah Sing", "Property"),
    "8583": ("Mah Sing", "Property"),
    "UEM Sunrise": ("UEM Sunrise", "Property"),
    "5148": ("UEM Sunrise", "Property"),
    "Eco World": ("Eco World", "Property"),
    "Eco World Development": ("Eco World", "Property"),
    "8206": ("Eco World", "Property"),
    "IOI Properties": ("IOI Properties", "Property"),
    "IOIPG": ("IOI Properties", "Property"),
    "5249": ("IOI Properties", "Property"),
    "Sime Darby Property": ("Sime Darby Property", "Property"),
    "SDPR": ("Sime Darby Property", "Property"),
    "5288": ("Sime Darby Property", "Property"),
    "IGB Bhd": ("IGB", "Property"),
    "IGB Berhad": ("IGB", "Property"),
    "1597": ("IGB", "Property"),
    "OSK Holdings": ("OSK Holdings", "Property"),
    "5053": ("OSK Holdings", "Property"),
    "YNH Property": ("YNH Property", "Property"),
    "3158": ("YNH Property", "Property"),
    "Tropicana": ("Tropicana Corporation", "Property"),
    "5401": ("Tropicana Corporation", "Property"),
    "LBS Bina": ("LBS Bina Group", "Property"),
    "5789": ("LBS Bina Group", "Property"),
    "Matrix Concepts": ("Matrix Concepts", "Property"),
    "5236": ("Matrix Concepts", "Property"),
    "Glomac": ("Glomac", "Property"),
    "5020": ("Glomac", "Property"),

    # ═══════════════════════════════════════════════════════════════
    # REITs (rate-cut beneficiaries)
    # ═══════════════════════════════════════════════════════════════
    "IGB REIT": ("IGB REIT", "REITs"),
    "5227": ("IGB REIT", "REITs"),
    "Sunway REIT": ("Sunway REIT", "REITs"),
    "SREIT": ("Sunway REIT", "REITs"),
    "5176": ("Sunway REIT", "REITs"),
    "KLCC REIT": ("KLCC REIT", "REITs"),
    "KLCCP Stapled": ("KLCC REIT", "REITs"),
    "KLCCP": ("KLCC REIT", "REITs"),
    "5235SS": ("KLCC REIT", "REITs"),
    "Pavilion REIT": ("Pavilion REIT", "REITs"),
    "5212": ("Pavilion REIT", "REITs"),
    "Axis REIT": ("Axis REIT", "REITs"),
    "5106": ("Axis REIT", "REITs"),
    "AmanahRaya REIT": ("AmanahRaya REIT", "REITs"),
    "5127": ("AmanahRaya REIT", "REITs"),
    "Sentral REIT": ("Sentral REIT", "REITs"),
    "5123": ("Sentral REIT", "REITs"),
    "YTL REIT": ("YTL REIT", "REITs"),
    "YTL Hospitality REIT": ("YTL REIT", "REITs"),
    "5109": ("YTL REIT", "REITs"),
    "Al-Aqar Healthcare REIT": ("Al-Aqar REIT", "REITs"),
    "Al-Aqar REIT": ("Al-Aqar REIT", "REITs"),
    "5116": ("Al-Aqar REIT", "REITs"),
    "Capitaland Malaysia Trust": ("Capitaland Malaysia Trust", "REITs"),
    "CLMT": ("Capitaland Malaysia Trust", "REITs"),
    "5180": ("Capitaland Malaysia Trust", "REITs"),
    "Hektar REIT": ("Hektar REIT", "REITs"),
    "5121": ("Hektar REIT", "REITs"),
    "UOA REIT": ("UOA REIT", "REITs"),
    "5110": ("UOA REIT", "REITs"),

    # ═══════════════════════════════════════════════════════════════
    # AVIATION & TRANSPORT
    # ═══════════════════════════════════════════════════════════════
    "AirAsia": ("Capital A", "Aviation"),
    "Capital A": ("Capital A", "Aviation"),
    "5099": ("Capital A", "Aviation"),
    "AirAsia X": ("AirAsia X", "Aviation"),
    "AAX": ("AirAsia X", "Aviation"),
    "5238": ("AirAsia X", "Aviation"),
    "Malaysia Airports": ("Malaysia Airports", "Aviation"),
    "MAHB": ("Malaysia Airports", "Aviation"),
    "5014": ("Malaysia Airports", "Aviation"),
    "Malaysia Airlines": ("Malaysia Airlines", "Aviation"),
    "MAB": ("Malaysia Airlines", "Aviation"),  # AMB
    "Westports Holdings": ("Westports", "Transport"),
    "Westports": ("Westports", "Transport"),
    "5246": ("Westports", "Transport"),
    "MMC Corp": ("MMC Corp", "Transport"),
    "MMC Corporation": ("MMC Corp", "Transport"),
    "2194": ("MMC Corp", "Transport"),
    "Pos Malaysia": ("Pos Malaysia", "Transport"),
    "4634": ("Pos Malaysia", "Transport"),
    "Tiong Nam Logistics": ("Tiong Nam Logistics", "Transport"),
    "8397": ("Tiong Nam Logistics", "Transport"),
    "GDex": ("GDex", "Transport"),
    "GD Express": ("GDex", "Transport"),
    "0078": ("GDex", "Transport"),

    # ═══════════════════════════════════════════════════════════════
    # AUTOMOTIVE
    # ═══════════════════════════════════════════════════════════════
    "UMW Holdings": ("UMW Holdings", "Auto"),
    "UMW": ("UMW Holdings", "Auto"),  # AMB
    "4588": ("UMW Holdings", "Auto"),
    "Bermaz Auto": ("Bermaz Auto", "Auto"),
    "BAuto": ("Bermaz Auto", "Auto"),
    "5248": ("Bermaz Auto", "Auto"),
    "MBMR": ("MBM Resources", "Auto"),
    "5983": ("MBM Resources", "Auto"),
    "DRB-Hicom": ("DRB-Hicom", "Auto"),
    "DRB Hicom": ("DRB-Hicom", "Auto"),
    "1619": ("DRB-Hicom", "Auto"),
    "Proton": ("Proton", "Auto"),
    "Perodua": ("Perodua", "Auto"),
    "APM Automotive": ("APM Automotive", "Auto"),
    "5015": ("APM Automotive", "Auto"),
    "Tan Chong Motor": ("Tan Chong Motor", "Auto"),
    "4405": ("Tan Chong Motor", "Auto"),

    # ═══════════════════════════════════════════════════════════════
    # CONGLOMERATES
    # ═══════════════════════════════════════════════════════════════
    "Sime Darby": ("Sime Darby", "Conglomerate"),
    "Sime Darby Bhd": ("Sime Darby", "Conglomerate"),
    "4197": ("Sime Darby", "Conglomerate"),
    "YTL Corporation": ("YTL Corp", "Conglomerate"),
    "YTL Corp": ("YTL Corp", "Conglomerate"),
    "YTL Bhd": ("YTL Corp", "Conglomerate"),
    "4677": ("YTL Corp", "Conglomerate"),
    "Berjaya Corp": ("Berjaya Corp", "Conglomerate"),
    "Berjaya Corporation": ("Berjaya Corp", "Conglomerate"),
    "3395": ("Berjaya Corp", "Conglomerate"),
    "Hong Leong Industries": ("Hong Leong Industries", "Conglomerate"),
    "HLI": ("Hong Leong Industries", "Conglomerate"),
    "3301": ("Hong Leong Industries", "Conglomerate"),
    "Genting Berhad": ("Genting", "Conglomerate"),
    "Genting Bhd": ("Genting", "Conglomerate"),
    "3182": ("Genting", "Conglomerate"),
    "Genting Malaysia": ("Genting Malaysia", "Consumer"),
    "GenM": ("Genting Malaysia", "Consumer"),
    "GENM": ("Genting Malaysia", "Consumer"),
    "4715": ("Genting Malaysia", "Consumer"),
    "Hap Seng Consolidated": ("Hap Seng Consolidated", "Conglomerate"),
    "3034": ("Hap Seng Consolidated", "Conglomerate"),
    "Batu Kawan": ("Batu Kawan", "Conglomerate"),
    "1899": ("Batu Kawan", "Conglomerate"),

    # ═══════════════════════════════════════════════════════════════
    # INSURANCE & FINANCIAL SERVICES
    # ═══════════════════════════════════════════════════════════════
    "Allianz Malaysia": ("Allianz Malaysia", "Insurance"),
    "1163": ("Allianz Malaysia", "Insurance"),
    "LPI Capital": ("LPI Capital", "Insurance"),
    "8621": ("LPI Capital", "Insurance"),
    "Syarikat Takaful Malaysia": ("Takaful Malaysia", "Insurance"),
    "Takaful Malaysia": ("Takaful Malaysia", "Insurance"),
    "6139": ("Takaful Malaysia", "Insurance"),
    "Manulife Holdings": ("Manulife Holdings", "Insurance"),
    "1058": ("Manulife Holdings", "Insurance"),
    "Bursa Malaysia Bhd": ("Bursa Malaysia", "Financial"),
    "1818": ("Bursa Malaysia", "Financial"),
    "Kenanga Investment": ("Kenanga Investment Bank", "Financial"),
    "6483": ("Kenanga Investment Bank", "Financial"),
    "RCE Capital": ("RCE Capital", "Financial"),
    "9296": ("RCE Capital", "Financial"),

    # ═══════════════════════════════════════════════════════════════
    # INDUSTRIAL / MATERIALS
    # ═══════════════════════════════════════════════════════════════
    "Press Metal": ("Press Metal Aluminium", "Materials"),
    "Press Metal Aluminium": ("Press Metal Aluminium", "Materials"),
    "8869": ("Press Metal Aluminium", "Materials"),
    "Ann Joo Resources": ("Ann Joo Resources", "Materials"),
    "6556": ("Ann Joo Resources", "Materials"),
    "Lion Industries": ("Lion Industries", "Materials"),
    "4235": ("Lion Industries", "Materials"),
    "Southern Steel": ("Southern Steel", "Materials"),
    "5665": ("Southern Steel", "Materials"),
    "Hume Cement": ("Hume Cement Industries", "Materials"),
    "5000": ("Hume Cement Industries", "Materials"),
    "Malayan Cement": ("Malayan Cement", "Materials"),
    "3794": ("Malayan Cement", "Materials"),
    "Cahya Mata Sarawak": ("Cahya Mata Sarawak", "Materials"),
    "CMS": ("Cahya Mata Sarawak", "Materials"),  # AMB
    "2852": ("Cahya Mata Sarawak", "Materials"),
    "Petra Energy": ("Petra Energy", "Materials"),
    "5133": ("Petra Energy", "Materials"),

    # ═══════════════════════════════════════════════════════════════
    # INDEX / MARKET INFRASTRUCTURE
    # ═══════════════════════════════════════════════════════════════
    "FBM KLCI": ("FBM KLCI", "Macro"),
    "KLCI": ("FBM KLCI", "Macro"),
    "Bursa Malaysia": ("Bursa Malaysia", "Macro"),
    "FBM Small Cap": ("FBM Small Cap", "Macro"),
    "FBM ACE": ("FBM ACE", "Macro"),
    "FBM Emas": ("FBM Emas", "Macro"),
}

# ═══════════════════════════════════════════════════════════════════
# MACRO KEYWORDS - Policy, global events, commodities with MYR/Bursa
# spillover but no specific company named.
# ═══════════════════════════════════════════════════════════════════
MACRO_KEYWORDS = {
    # ─── Central banks & monetary policy ───
    "Fed": "Macro",
    "FOMC": "Macro",
    "Federal Reserve": "Macro",
    "Jerome Powell": "Macro",
    "ECB": "Macro",
    "European Central Bank": "Macro",
    "BOJ": "Macro",
    "Bank of Japan": "Macro",
    "PBOC": "Macro",
    "People's Bank of China": "Macro",
    "BNM": "Macro",
    "Bank Negara": "Macro",
    "Bank Negara Malaysia": "Macro",
    "OPR": "Macro",
    "overnight policy rate": "Macro",
    "rate cut": "Macro",
    "rate hike": "Macro",
    "rate decision": "Macro",
    "interest rate": "Macro",
    "monetary policy": "Macro",
    "quantitative easing": "Macro",
    "Middle East": "Macro",  # oil geopolitics
    "Federal Territories": "Macro",  # KL/Putrajaya policy
    "Works Minister": "Macro",  # infra spending
    "National Housing Policy": "Macro",
    "Joint Action Plan": "Macro",
    "Bob Iger": "Consumer",  # Disney CEO, streaming/media
    "Nelson Peltz": "Macro",  # activist investor
    "Sabah Cabinet": "Macro",
    "Sarawak government": "Macro",
    "Housing Minister": "Macro",
    "Transport Minister": "Macro",
    "Big Oil": "OilGas",
    "Chinese AI": "Tech",
    "1MDB": "Macro",
    "Jho Low": "Macro",


    # ─── Malaysia government / policy ───
    "MOF": "Macro",
    "Ministry of Finance": "Macro",
    "Anwar Ibrahim": "Macro",
    "PM Anwar": "Macro",
    "Rafizi Ramli": "Macro",
    "Amir Hamzah": "Macro",
    "Madani": "Macro",
    "Budget 2026": "Macro",
    "Budget 2027": "Macro",
    "Budget 2028": "Macro",
    "sales and service tax": "Macro",
    "capital gains tax": "Macro",
    "CGT": "Macro",  # AMB
    "subsidy": "Macro",
    "subsidy rationalisation": "Macro",
    "diesel subsidy": "Macro",
    "RON95": "Macro",
    "RON97": "Macro",
    "targeted subsidy": "Macro",
    "PADU": "Macro",  # subsidy database
    "EPF": "Macro",
    "Employees Provident Fund": "Macro",
    "KWAP": "Macro",
    "Khazanah": "Macro",
    "PNB": "Macro",  # AMB - Permodalan Nasional
    "Permodalan Nasional": "Macro",
    "GLIC": "Macro",
    "government-linked": "Macro",

    # ─── Global trade / geopolitics ───
    "tariff": "Macro",
    "Trump tariff": "Macro",
    "trade war": "Macro",
    "supply chain": "Macro",
    "recession": "Macro",
    "soft landing": "Macro",
    "hard landing": "Macro",
    "US election": "Macro",
    "China stimulus": "Macro",
    "ASEAN summit": "Macro",
    "geopolitical": "Macro",

    # ─── Currency ───
    "USD/MYR": "Macro",
    "MYR/USD": "Macro",
    "ringgit": "Macro",
    "ringgit weakness": "Macro",
    "ringgit strength": "Macro",
    "DXY": "Macro",
    "dollar index": "Macro",
    "US dollar": "Macro",
    "capital outflow": "Macro",
    "capital inflow": "Macro",
    "foreign fund": "Macro",
    "foreign inflow": "Macro",
    "foreign outflow": "Macro",
    "net foreign buying": "Macro",
    "net foreign selling": "Macro",

    # ─── Bond markets / rates ───
    "US Treasury": "Macro",
    "US Treasury yield": "Macro",
    "10-year yield": "Macro",
    "2-year yield": "Macro",
    "yield curve": "Macro",
    "inverted yield curve": "Macro",
    "MGS": "Macro",  # Malaysian Govt Securities
    "Malaysian Government Securities": "Macro",
    "bond yield": "Macro",
    "sukuk": "Banking",

    # ─── Economic indicators ───
    "CPI": "Macro",
    "consumer price index": "Macro",
    "PPI": "Macro",
    "producer price index": "Macro",
    "inflation": "Macro",
    "deflation": "Macro",
    "GDP": "Macro",
    "GDP growth": "Macro",
    "unemployment": "Macro",
    "jobless claims": "Macro",
    "nonfarm payrolls": "Macro",
    "NFP": "Macro",
    "PMI": "Macro",
    "China PMI": "Macro",
    "manufacturing PMI": "Macro",
    "industrial production": "Macro",
    "retail sales": "Macro",
    "trade balance": "Macro",
    "current account": "Macro",

    # ─── Commodities: energy ───
    "crude oil": "OilGas",
    "Brent": "OilGas",
    "WTI": "OilGas",
    "OPEC": "OilGas",
    "OPEC+": "OilGas",
    "oil price": "OilGas",
    "oil supply": "OilGas",
    "oil demand": "OilGas",
    "natural gas": "OilGas",
    "LNG": "OilGas",

    # ─── Commodities: soft ───
    "CPO": "Plantation",
    "palm oil": "Plantation",
    "palm oil price": "Plantation",
    "crude palm oil": "Plantation",
    "MPOB": "Plantation",  # Malaysian Palm Oil Board
    "palm oil stockpile": "Plantation",
    "palm oil export": "Plantation",
    "soybean": "Plantation",  # competes with palm
    "soybean oil": "Plantation",
    "rubber": "Plantation",

    # ─── Commodities: metals ───
    "gold price": "Materials",
    "iron ore": "Materials",
    "copper": "Materials",
    "aluminium": "Materials",
    "aluminum": "Materials",
    "nickel": "Materials",
    "steel": "Materials",
    "coal": "Materials",

    # ─── Tech themes (2024-26) ───
    "data center": "Tech",
    "data centre": "Tech",
    "AI infrastructure": "Tech",
    "artificial intelligence": "Tech",
    "semiconductor": "Tech",
    "chip shortage": "Tech",
    "Nvidia": "Tech",
    "TSMC": "Tech",
    "hyperscaler": "Tech",
    "cloud computing": "Tech",
    "5G rollout": "Tech",

    # ─── Real estate / infra themes ───
    "Johor-Singapore SEZ": "Property",
    "JS-SEZ": "Property",
    "Johor SEZ": "Property",
    "Special Economic Zone": "Property",
    "ECRL": "Construction",
    "East Coast Rail Link": "Construction",
    "MRT3": "Construction",
    "MRT Circle Line": "Construction",
    "Penang LRT": "Construction",
    "high-speed rail": "Construction",
    "KL-Singapore HSR": "Construction",
    "Pan Borneo Highway": "Construction",

    # ─── Energy transition ───
    "renewable energy": "Utilities",
    "solar": "Utilities",
    "NETR": "Utilities",  # National Energy Transition Roadmap
    "energy transition": "Utilities",
    "hydrogen": "Utilities",
    "green energy": "Utilities",
    "carbon credit": "Utilities",

    # ─── Market structure ───
    "IPO": "Macro",
    "listing": "Macro",
    "delisting": "Macro",
    "PN17": "Macro",
    "GN3": "Macro",
    "short selling": "Macro",
    "regulated short selling": "Macro",
    "intraday short selling": "Macro",
    "IDSS": "Macro",
    "buyback": "Macro",
    "share buyback": "Macro",

    # ─── Sector-specific policies ───
    "PayNet": "Banking",
    "Bursa suspension": "Macro",
    "MFRS": "Banking",  # Malaysian Financial Reporting Standards
    "Basel III": "Banking",
    "loan growth": "Banking",
    "NPL": "Banking",
    "non-performing loan": "Banking",
    "car loan": "Banking",
    "housing loan": "Banking",
}
